### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by kaweepatinn1**

### CODE REVIEW

**Review by Imabanana80 — CHANGES_REQUESTED** [review]
Change it to just "Gerald"

**Comment by kaweepatinn1** [comment]
LMAO

**Comment by kaweepatinn1** [comment]
me after trying to take the "Gerald" copyright https://www.google.com/search?q=gerald&oq=gerald&aqs=chrome.0.0i355i512j46i512l4j69i60l3.575j0j7&sourceid=chrome&ie=UTF-8

**Comment by Imabanana80** [comment]
Nerd

**Pull request merged**
